<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdmModulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'name' => 'Notifications',
                'icon' => 'fa fa-cog',
                'path' => 'notifications',
                'table_name' => 'adm_notifications',
                'controller' => 'NotificationsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Privileges',
                'icon' => 'fa fa-crown',
                'path' => 'privileges',
                'table_name' => 'adm_privileges',
                'controller' => 'PrivilegesController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Users Management',
                'icon' => 'fa fa-users',
                'path' => 'users',
                'table_name' => 'adm_users',
                'controller' => 'AdminUsersController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'App Settings',
                'icon' => 'fa fa-cog',
                'path' => 'settings',
                'table_name' => 'adm_settings',
                'controller' => 'SettingsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Module Generator',
                'icon' => 'fa fa-th',
                'path' => 'module_generator',
                'table_name' => 'adm_moduls',
                'controller' => 'ModulsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Menu Management',
                'icon' => 'fa fa-bars',
                'path' => 'menu_management',
                'table_name' => 'adm_menus',
                'controller' => 'MenusController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Email Templates',
                'icon' => 'fa fa-envelope-o',
                'path' => 'email_templates',
                'table_name' => 'adm_email_templates',
                'controller' => 'EmailTemplatesController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Statistic Builder',
                'icon' => 'fa fa-dashboard',
                'path' => 'statistic_builder',
                'table_name' => 'adm_statistics',
                'controller' => 'StatisticBuilderController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'API Generator',
                'icon' => 'fa fa-cloud-download',
                'path' => 'api_generator',
                'table_name' => '',
                'controller' => 'AdminApiController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Announcements',
                'icon' => 'fa fa-info-circle',
                'path' => 'announcements',
                'table_name' => 'announcements',
                'controller' => 'AnnouncementsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Log User Access',
                'icon' => 'fa fa-history',
                'path' => 'logs',
                'table_name' => 'adm_logs',
                'controller' => 'LogsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dashboard',
                'icon' => 'fa-solid fa-chart-simple',
                'path' => 'dashboard',
                'table_name' => 'dashboard',
                'controller' => 'Dashboard\DashboardController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            // FOR NEW MODULES 

            [
                'name' => 'Brands',
                'icon' => 'fa-regular fa-circle',
                'path' => 'brands',
                'table_name' => 'brands',
                'controller' => 'Brands\BrandsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Brand Directions',
                'icon' => 'fa-regular fa-circle',
                'path' => 'brand_directions',
                'table_name' => 'brand_directions',
                'controller' => 'BrandDirections\BrandDirectionsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Brand Groups',
                'icon' => 'fa-regular fa-circle',
                'path' => 'brand_groups',
                'table_name' => 'brand_groups',
                'controller' => 'BrandGroups\BrandGroupsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Brand Marketings',
                'icon' => 'fa-regular fa-circle',
                'path' => 'brand_marketings',
                'table_name' => 'brand_marketings',
                'controller' => 'BrandMarketings\BrandMarketingsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'categories',
                'table_name' => 'categories',
                'controller' => 'Categories\CategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'classifications',
                'table_name' => 'classifications',
                'controller' => 'Classifications\ClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Colors',
                'icon' => 'fa-regular fa-circle',
                'path' => 'colors',
                'table_name' => 'colors',
                'controller' => 'Colors\ColorsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Counters',
                'icon' => 'fa-regular fa-circle',
                'path' => 'counters',
                'table_name' => 'counters',
                'controller' => 'Counters\CountersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Currencies',
                'icon' => 'fa-regular fa-circle',
                'path' => 'currencies',
                'table_name' => 'currencies',
                'controller' => 'Currencies\CurrenciesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Brands',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_brands',
                'table_name' => 'gashapon_brands',
                'controller' => 'GashaponBrands\GashaponBrandsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_categories',
                'table_name' => 'gashapon_categories',
                'controller' => 'GashaponCategories\GashaponCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Countries',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_countries',
                'table_name' => 'gashapon_countries',
                'controller' => 'GashaponCountries\GashaponCountriesController',
                'is_protected' => 0,
                'is_active' => 1,
            ],
            
            [
                'name' => 'Gashapon Incoterms',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_incoterms',
                'created_at' => date('Y-m-d H:i:s'),
                'table_name' => 'gashapon_incoterms',
                'controller' => 'GashaponIncoterms\GashaponIncotermsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Inventory Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_inventory_types',
                'table_name' => 'gashapon_inventory_types',
                'controller' => 'GashaponInventoryTypes\GashaponInventoryTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Models',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_models',
                'table_name' => 'gashapon_models',
                'controller' => 'GashaponModels\GashaponModelsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Item Masters',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_item_masters',
                'table_name' => 'gashapon_item_masters',
                'controller' => 'GashaponItemMasters\GashaponItemMastersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Product Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_product_types',
                'table_name' => 'gashapon_product_types',
                'controller' => 'GashaponProductTypes\GashaponProductTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon SKU Statuses',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_sku_statuses',
                'table_name' => 'gashapon_sku_statuses',
                'controller' => 'GashaponSkuStatuses\GashaponSkuStatusesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon UOMs',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_uoms',
                'table_name' => 'gashapon_uoms',
                'controller' => 'GashaponUoms\GashaponUomsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Vendor Groups',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_vendor_groups',
                'table_name' => 'gashapon_vendor_groups',
                'controller' => 'GashaponVendorGroups\GashaponVendorGroupsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Vendor Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_vendor_types',
                'table_name' => 'gashapon_vendor_types',
                'controller' => 'GashaponVendorTypes\GashaponVendorTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Warehouse Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_warehouse_categories',
                'table_name' => 'gashapon_warehouse_categories',
                'controller' => 'GashaponWarehouseCategories\GashaponWarehouseCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Identifiers',
                'icon' => 'fa-regular fa-circle',
                'path' => 'identifiers',
                'table_name' => 'identifiers',
                'controller' => 'Identifiers\IdentifiersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Incoterms',
                'icon' => 'fa-regular fa-circle',
                'path' => 'incoterms',
                'table_name' => 'incoterms',
                'controller' => 'Incoterms\IncotermsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Inventory Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'inventory_types',
                'table_name' => 'inventory_types',
                'controller' => 'InventoryTypes\InventoryTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Master',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_masters',
                'table_name' => 'item_masters',
                'controller' => 'ItemMasters\ItemMastersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Platforms',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_platforms',
                'table_name' => 'item_platforms',
                'controller' => 'ItemPlatforms\ItemPlatformsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Promo Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_promo_types',
                'table_name' => 'item_promo_types',
                'controller' => 'ItemPromoTypes\ItemPromoTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Segmentations',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_segmentations',
                'table_name' => 'item_segmentations',
                'controller' => 'ItemSegmentations\ItemSegmentationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Serials',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_serials',
                'table_name' => 'item_serials',
                'controller' => 'ItemSerials\ItemSerialsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Margin Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'margin_categories',
                'table_name' => 'margin_categories',
                'controller' => 'MarginCategories\MarginCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Model Specifics',
                'icon' => 'fa-regular fa-circle',
                'path' => 'model_specifics',
                'table_name' => 'model_specifics',
                'controller' => 'ModelSpecifics\ModelSpecificsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Platforms',
                'icon' => 'fa-regular fa-circle',
                'path' => 'platforms',
                'table_name' => 'platforms',
                'controller' => 'Platforms\PlatformsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Promo Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'promo_types',
                'table_name' => 'promo_types',
                'controller' => 'PromoTypes\PromoTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_categories',
                'table_name' => 'rma_categories',
                'controller' => 'RmaCategories\RmaCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_classifications',
                'table_name' => 'rma_classifications',
                'controller' => 'RmaClassifications\RmaClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA Margin Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_margin_categories',
                'table_name' => 'rma_margin_categories',
                'controller' => 'RmaMarginCategories\RmaMarginCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA Model Specifics',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_model_specifics',
                'table_name' => 'rma_model_specifics',
                'controller' => 'RmaModelSpecifics\RmaModelSpecificsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA Store Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_store_categories',
                'table_name' => 'rma_store_categories',
                'controller' => 'RmaStoreCategories\RmaStoreCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA Sub Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_sub_classifications',
                'table_name' => 'rma_sub_classifications',
                'controller' => 'RmaSubClassifications\RmaSubClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'RMA UOMs',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_uoms',
                'table_name' => 'rma_uoms',
                'controller' => 'RmaUoms\RmaUomsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Segmentations',
                'icon' => 'fa-regular fa-circle',
                'path' => 'segmentations',
                'table_name' => 'segmentations',
                'controller' => 'Segmentations\SegmentationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Sizes',
                'icon' => 'fa-regular fa-circle',
                'path' => 'sizes',
                'table_name' => 'sizes',
                'controller' => 'Sizes\SizesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'SKU Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'sku_classifications',
                'table_name' => 'sku_classifications',
                'controller' => 'SkuClassifications\SkuClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'SKU Legends',
                'icon' => 'fa-regular fa-circle',
                'path' => 'sku_legends',
                'table_name' => 'sku_legends',
                'controller' => 'SkuLegends\SkuLegendsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'SKU Statuses',
                'icon' => 'fa-regular fa-circle',
                'path' => 'sku_statuses',
                'table_name' => 'sku_statuses',
                'controller' => 'SkuStatuses\SkuStatusesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Store Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'store_categories',
                'table_name' => 'store_categories',
                'controller' => 'StoreCategories\StoreCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Sub Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'sub_categories',
                'table_name' => 'sub_categories',
                'controller' => 'SubCategories\SubCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Sub Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'sub_classifications',
                'table_name' => 'sub_classifications',
                'controller' => 'SubClassifications\SubClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Support Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'support_types',
                'table_name' => 'support_types',
                'controller' => 'SupportTypes\SupportTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'UOMs',
                'icon' => 'fa-regular fa-circle',
                'path' => 'uoms',
                'table_name' => 'uoms',
                'controller' => 'Uoms\UomsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Vendors',
                'icon' => 'fa-regular fa-circle',
                'path' => 'vendors',
                'table_name' => 'vendors',
                'controller' => 'Vendors\VendorsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            
            [
                'name' => 'Vendor Groups',
                'icon' => 'fa-regular fa-circle',
                'path' => 'vendor_groups',
                'table_name' => 'vendor_groups',
                'controller' => 'VendorGroups\VendorGroupsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Vendor Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'vendor_types',
                'table_name' => 'vendor_types',
                'controller' => 'VendorTypes\VendorTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Warehouse Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'warehouse_categories',
                'table_name' => 'warehouse_categories',
                'controller' => 'WarehouseCategories\WarehouseCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Warranties',
                'icon' => 'fa-regular fa-circle',
                'path' => 'warranties',
                'table_name' => 'warranties',
                'controller' => 'Warranties\WarrantiesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Apple LOBs',
                'icon' => 'fa-regular fa-circle',
                'path' => 'apple_lobs',
                'table_name' => 'apple_lobs',
                'controller' => 'AppleLobs\AppleLobsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'System Error Logs',
                'icon' => 'fa fa-history',
                'path' => 'system_error_logs',
                'table_name' => 'log_system_errors',
                'controller' => 'SystemErrorLogsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Action Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'action_types',
                'table_name' => 'action_types',
                'controller' => 'ActionTypes\ActionTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Table Setting',
                'icon' => 'fa-solid fa-sliders',
                'path' => 'table_settings',
                'table_name' => 'table_settings',
                'controller' => 'TableSettings\TableSettingsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Module Headers',
                'icon' => 'fa-regular fa-circle',
                'path' => 'module_headers',
                'table_name' => 'module_headers',
                'controller' => 'ModuleHeaders\ModuleHeadersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Master Approval',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_master_approvals',
                'table_name' => 'item_master_approvals',
                'controller' => 'ItemMasterApprovals\ItemMasterApprovalsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Item Master Approval',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_item_master_approvals',
                'table_name' => 'gashapon_item_master_approvals',
                'controller' => 'GashaponItemMasterApprovals\GashaponItemMasterApprovalsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Item Master History',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_master_histories',
                'table_name' => 'item_master_histories',
                'controller' => 'ItemMasterHistories\ItemMasterHistoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],

            [
                'name' => 'Gashapon Item Master History',
                'icon' => 'fa-regular fa-circle',
                'path' => 'gashapon_item_master_histories',
                'table_name' => 'gashapon_item_master_histories',
                'controller' => 'GashaponItemMasterHistories\GashaponItemMasterHistoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Module Activity History',
                'icon' => 'fa fa-history',
                'path' => 'module_activity_history',
                'table_name' => 'module_activity_history',
                'controller' => 'ModuleActivityHistoryController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'RMA Item Master',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_item_masters',
                'table_name' => 'rma_item_masters',
                'controller' => 'RmaItemMasters\RmaItemMastersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'RMA Item Master Approval',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_item_master_approvals',
                'table_name' => 'rma_item_master_approvals',
                'controller' => 'RmaItemMasterApprovals\RmaItemMasterApprovalsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'RMA Item Master History',
                'icon' => 'fa-regular fa-circle',
                'path' => 'rma_item_master_histories',
                'table_name' => 'rma_item_master_histories',
                'controller' => 'RmaItemMasterHistories\RmaItemMasterHistoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Item Master Approval (Accounting)',
                'icon' => 'fa-regular fa-circle',
                'path' => 'item_master_accounting_approvals',
                'table_name' => 'item_master_accounting_approvals',
                'controller' => 'ItemMasterAccountingApprovals\ItemMasterAccountingApprovalsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Margin Matrix',
                'icon' => 'fa-regular fa-circle',
                'path' => 'margin_matrices',
                'table_name' => 'margin_matrices',
                'controller' => 'MarginMatrices\MarginMatricesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Margin Matrix (ECOMM)',
                'icon' => 'fa-regular fa-circle',
                'path' => 'ecomm_margin_matrices',
                'table_name' => 'ecomm_margin_matrices',
                'controller' => 'EcommMarginMatrices\EcommMarginMatricesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Brands',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_brands',
                'table_name' => 'admin_brands',
                'controller' => 'AdminBrands\AdminBrandsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_categories',
                'table_name' => 'admin_categories',
                'controller' => 'AdminCategories\AdminCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_classifications',
                'table_name' => 'admin_classifications',
                'controller' => 'AdminClassifications\AdminClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Colors',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_colors',
                'table_name' => 'admin_colors',
                'controller' => 'AdminColors\AdminColorsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Currencies',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_currencies',
                'table_name' => 'admin_currencies',
                'controller' => 'AdminCurrencies\AdminCurrenciesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Incoterms',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_incoterms',
                'table_name' => 'admin_incoterms',
                'controller' => 'AdminIncoterms\AdminIncotermsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Inventories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_inventories',
                'table_name' => 'admin_inventories',
                'controller' => 'AdminInventories\AdminInventoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Item Master',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_item_masters',
                'table_name' => 'admin_item_masters',
                'controller' => 'AdminItemMasters\AdminItemMastersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Margin Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_margin_categories',
                'table_name' => 'admin_margin_categories',
                'controller' => 'AdminMarginCategories\AdminMarginCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Model Specifics',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_model_specifics',
                'table_name' => 'admin_model_specifics',
                'controller' => 'AdminModelSpecifics\AdminModelSpecificsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Sizes',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_sizes',
                'table_name' => 'admin_sizes',
                'controller' => 'AdminSizes\AdminSizesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Sku Legends',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_sku_legends',
                'table_name' => 'admin_sku_legends',
                'controller' => 'AdminSkuLegends\AdminSkuLegendsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Sku Statuses',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_sku_statuses',
                'table_name' => 'admin_sku_statuses',
                'controller' => 'AdminSkuStatuses\AdminSkuStatusesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Store Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_store_categories',
                'table_name' => 'admin_store_categories',
                'controller' => 'AdminStoreCategories\AdminStoreCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Sub Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_sub_categories',
                'table_name' => 'admin_sub_categories',
                'controller' => 'AdminSubCategories\AdminSubCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Sub Classifications',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_sub_classifications',
                'table_name' => 'admin_sub_classifications',
                'controller' => 'AdminSubClassifications\AdminSubClassificationsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Suppliers',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_suppliers',
                'table_name' => 'admin_suppliers',
                'controller' => 'AdminSuppliers\AdminSuppliersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Uoms',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_uoms',
                'table_name' => 'admin_uoms',
                'controller' => 'AdminUoms\AdminUomsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Vendors',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_vendors',
                'table_name' => 'admin_vendors',
                'controller' => 'AdminVendors\AdminVendorsController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Vendor Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_vendor_types',
                'table_name' => 'admin_vendor_types',
                'controller' => 'AdminVendorTypes\AdminVendorTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Warehouse Categories',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_warehouse_categories',
                'table_name' => 'admin_warehouse_categories',
                'controller' => 'AdminWarehouseCategories\AdminWarehouseCategoriesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Warranties',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_warranties',
                'table_name' => 'admin_warranties',
                'controller' => 'AdminWarranties\AdminWarrantiesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Admin Brand Types',
                'icon' => 'fa-regular fa-circle',
                'path' => 'admin_brand_types',
                'table_name' => 'admin_brand_types',
                'controller' => 'AdminBrandTypes\AdminBrandTypesController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ];

        foreach ($data as $module) {
            DB::table('adm_modules')->updateOrInsert(['name' => $module['name']], $module);
        }

    }
}