const useThemeStyles = (theme) => {

    const styles = {
        textColor: {
            'bg-skin-blue': 'text-black',
            'bg-skin-blue-light': 'text-black',
            'bg-skin-yellow': 'text-black',
            'bg-skin-yellow-light': 'text-black',
            'bg-skin-green': 'text-black',
            'bg-skin-green-light': 'text-black',
            'bg-skin-purple': 'text-black',
            'bg-skin-purple-light': 'text-black',
            'bg-skin-red': 'text-black',
            'bg-skin-red-light': 'text-black',
            'bg-skin-black': 'text-gray-300',
            'bg-skin-black-light': 'text-black',
            'bg-skin-white': 'text-black',
        },
        hoverTextColor: {
            'bg-skin-blue': 'hover:text-white',
            'bg-skin-blue-light': 'hover:text-white',
            'bg-skin-yellow': 'hover:text-white',
            'bg-skin-yellow-light': 'hover:text-white',
            'bg-skin-green': 'hover:text-white',
            'bg-skin-green-light': 'hover:text-white',
            'bg-skin-purple': 'hover:text-white',
            'bg-skin-purple-light': 'hover:text-white',
            'bg-skin-red': 'hover:text-white',
            'bg-skin-red-light': 'hover:text-white',
            'bg-skin-black': 'hover:text-gray-100',
            'bg-skin-black-light': 'hover:text-black',
            'bg-skin-white': 'hover:text-white',
        },
        textColorActive: {
            'bg-skin-blue': 'text-white',
            'bg-skin-blue-light': 'text-white',
            'bg-skin-yellow': 'text-white',
            'bg-skin-yellow-light': 'text-white',
            'bg-skin-green': 'text-white',
            'bg-skin-green-light': 'text-white',
            'bg-skin-purple': 'text-white',
            'bg-skin-purple-light': 'text-white',
            'bg-skin-red': 'text-white',
            'bg-skin-red-light': 'text-white',
            'bg-skin-black': 'text-gray-400',
            'bg-skin-black-light': 'text-black',
            'bg-skin-white': 'text-white',
        },
        bgColor: {
            'bg-skin-blue': 'bg-white',
            'bg-skin-blue-light': 'bg-white',
            'bg-skin-yellow': 'bg-white',
            'bg-skin-yellow-light': 'bg-white',
            'bg-skin-green': 'bg-white',
            'bg-skin-green-light': 'bg-white',
            'bg-skin-purple': 'bg-white',
            'bg-skin-purple-light': 'bg-white',
            'bg-skin-red': 'bg-white',
            'bg-skin-red-light': 'bg-white',
            'bg-skin-black': 'bg-white',
            'bg-skin-black-light': 'bg-white',
            'bg-skin-white': 'bg-stone-900',
        },
        borderColor: {
            'bg-skin-blue': 'border-white',
            'bg-skin-blue-light': 'border-white',
            'bg-skin-yellow': 'border-white',
            'bg-skin-yellow-light': 'border-white',
            'bg-skin-green': 'border-white',
            'bg-skin-green-light': 'border-white',
            'bg-skin-purple': 'border-white',
            'bg-skin-purple-light': 'border-white',
            'bg-skin-red': 'border-white',
            'bg-skin-red-light': 'border-white',
            'bg-skin-black': 'border-gray-400',
            'bg-skin-black-light': 'border-white',
            'bg-skin-white': 'border-gray-400',
        },
        tooltipColor: {
            "skin-blue": "bg-skin-blue-light",
            "skin-blue-light": "bg-skin-blue",
            "skin-yellow": "bg-skin-yellow-light",
            "skin-yellow-light": "bg-skin-yellow",
            "skin-green": "bg-skin-green-light",
            "skin-green-light": "bg-green-yellow",
            "skin-purple": "bg-skin-purple-light",
            "skin-purple-light": "bg-skin-purple",
            "skin-red": "bg-skin-red-light",
            "skin-red-light": "bg-skin-red",
            "skin-black": "bg-skin-black-light",
            "skin-black-light": "bg-skin-black",
            "skin-white": 'bg-skin-white-light',
        },
        arrwoTooltipColor: {
            'skin-blue': '#508C9B',
            'skin-blue-light': '#134B70',
            'skin-yellow': '#FFF455',
            'skin-yellow-light': '#F4CE14',
            'skin-green': '#508D4E',
            'skin-green-light': '#1A5319',
            'skin-purple': '#BC5A94',
            'skin-purple-light': '#F075AA',
            'skin-red': '#E72929',
            'skin-red-light': '#C40C0C',
            'skin-black': '#31363F',
            'skin-black-light': '#322C2B',
            'skin-white': '#e9f3f5',
        },
        buttonSwalColor: {
            'bg-skin-blue': '#134B70',
            'bg-skin-blue-light': '#508C9B',
            'bg-skin-yellow': '#F4CE14',
            'bg-skin-yellow-light': '#FFF455',
            'bg-skin-green': '#1A5319',
            'bg-skin-green-light': '#508D4E',
            'bg-skin-purple': '#BC5A94',
            'bg-skin-purple-light': '#F075AA',
            'bg-skin-red': '#C40C0C',
            'bg-skin-red-light': '#E72929',
            'bg-skin-black': '#322C2B',
            'bg-skin-black-light': '#31363F',
            'bg-skin-white': '#60A5FA',
        },
        paginationHoverColor: {
            "bg-skin-blue": "hover:bg-skin-blue-light",
            "bg-skin-blue-light": "hover:bg-skin-blue",
            "bg-skin-yellow": "hover:bg-skin-yellow-light",
            "bg-skin-yellow-light": "hover:bg-skin-yellow",
            "bg-skin-green": "hover:bg-skin-green-light",
            "bg-skin-green-light": "hover:bg-skin-green",
            "bg-skin-purple": "hover:bg-skin-purple-light",
            "bg-skin-purple-light": "hover:bg-skin-purple",
            "bg-skin-red": "hover:bg-skin-red-light",
            "bg-skin-red-light": "hover:bg-skin-red",
            "bg-skin-black": "hover:bg-skin-black-light",
            "bg-skin-black-light": "hover:bg-skin-black",
            "bg-skin-white": "hover:bg-skin-white-light",
        },
        hoverColor: {
            "bg-skin-blue": "hover:bg-skin-blue",
            "bg-skin-blue-light": "hover:bg-skin-blue-light",
            "bg-skin-yellow": "hover:bg-skin-yellow",
            "bg-skin-yellow-light": "hover:bg-skin-yellow-light",
            "bg-skin-green": "hover:bg-skin-green",
            "bg-skin-green-light": "hover:bg-skin-green-light",
            "bg-skin-purple": "hover:bg-skin-purple",
            "bg-skin-purple-light": "hover:bg-skin-purple-light",
            "bg-skin-red": "hover:bg-skin-red",
            "bg-skin-red-light": "hover:bg-skin-red-light",
            "bg-skin-black": "hover:bg-skin-black-hover",
            "bg-skin-black-light": "hover:bg-skin-black-light",
            "bg-skin-white": "hover:bg-skin-black",
        },
        primayActiveColor: {
            "bg-skin-blue": "bg-skin-blue-light",
            "bg-skin-blue-light": "bg-skin-blue",
            "bg-skin-yellow": "bg-skin-yellow-light",
            "bg-skin-yellow-light": "bg-skin-yellow",
            "bg-skin-green": "bg-skin-green-light",
            "bg-skin-green-light": "bg-skin-green",
            "bg-skin-purple": "bg-skin-purple-light",
            "bg-skin-purple-light": "bg-skin-purple",
            "bg-skin-red": "bg-skin-red-light",
            "bg-skin-red-light": "bg-skin-red",
            "bg-skin-black": "bg-skin-white",
            "bg-skin-black-light": "bg-skin-black",
            "bg-skin-white": "bg-skin-black"
        },
        paginationSideActiveColor: {
            "bg-skin-blue": "bg-skin-blue-light",
            "bg-skin-blue-light": "bg-skin-blue",
            "bg-skin-yellow": "bg-skin-yellow-light",
            "bg-skin-yellow-light": "bg-skin-yellow",
            "bg-skin-green": "bg-skin-green-light",
            "bg-skin-green-light": "bg-skin-green",
            "bg-skin-purple": "bg-skin-purple-light",
            "bg-skin-purple-light": "bg-skin-purple",
            "bg-skin-red": "bg-skin-red-light",
            "bg-skin-red-light": "bg-skin-red",
            "bg-skin-black": "bg-skin-black-light",
            "bg-skin-black-light": "bg-skin-black",
            "bg-skin-white": "bg-skin-white-light"
        },
        borderTheme: {
            'bg-skin-blue': 'border-teal-500',
            'bg-skin-blue-light': 'border-cyan-700',
            'bg-skin-yellow': 'border-yellow-500',
            'bg-skin-yellow-light': 'border-yellow-400',
            'bg-skin-green': 'border-green-500',
            'bg-skin-green-light': 'border-green-400',
            'bg-skin-purple': 'border-fuchsia-400',
            'bg-skin-purple-light': 'border-fuchsia-400',
            'bg-skin-red': 'border-red-500',
            'bg-skin-red-light': 'border-red-400',
            'bg-skin-black': 'border-black',
            'bg-skin-black-light': 'border-black',
            'bg-skin-white': 'border-blue-300',
        },
        secondaryHoverBorderTheme: {
            'bg-skin-blue': 'hover:border-teal-500',
            'bg-skin-blue-light': 'hover:border-cyan-700',
            'bg-skin-yellow': 'hover:border-yellow-500',
            'bg-skin-yellow-light': 'hover:border-yellow-400',
            'bg-skin-green': 'hover:border-green-500',
            'bg-skin-green-light': 'hover:border-green-400',
            'bg-skin-purple': 'hover:border-fuchsia-400',
            'bg-skin-purple-light': 'hover:border-fuchsia-400',
            'bg-skin-red': 'hover:border-red-500',
            'bg-skin-red-light': 'hover:border-red-400',
            'bg-skin-black': 'hover:border-black',
            'bg-skin-black-light': 'hover:border-black',
            'bg-skin-white': 'hover:border-blue-300',
        },

        calendarDateTimeColor: {
            'bg-skin-blue': 'bg-skin-white-light',
            'bg-skin-blue-light': 'bg-skin-white-light',
            'bg-skin-yellow': 'bg-skin-yellow-light',
            'bg-skin-yellow-light': 'bg-skin-yellow-light',
            'bg-skin-green': 'bg-skin-green-light',
            'bg-skin-green-light': 'bg-skin-green-light',
            'bg-skin-purple': 'bg-skin-purple-light',
            'bg-skin-purple-light': 'bg-skin-purple-light',
            'bg-skin-red': 'bg-skin-red-light',
            'bg-skin-red-light': 'bg-skin-red-light',
            'bg-skin-black': 'bg-skin-black-hover',
            'bg-skin-black-light': 'bg-skin-black-light',
            'bg-skin-white': 'bg-skin-white-light',
        },

        iconThemeColor : {
            'bg-skin-blue': 'text-sky-900',
            'bg-skin-blue-light': 'text-cyan-800',
            'bg-skin-yellow': 'text-amber-600',
            'bg-skin-yellow-light': 'text-amber-300',
            'bg-skin-green': 'text-green-700',
            'bg-skin-green-light': 'text-green-700',
            'bg-skin-purple': 'text-pink-800',
            'bg-skin-purple-light': 'text-pink-600',
            'bg-skin-red': 'text-red-600',
            'bg-skin-red-light': 'text-red-600',
            'bg-skin-black': 'text-gray-400',
            'bg-skin-black-light': 'text-gray-800',
            'bg-skin-white': 'text-sky-700',
        },
        scrollbarTheme: {
            'bg-skin-blue': 'scrollbar-thumb-sky-900',
            'bg-skin-blue-light': 'scrollbar-thumb-cyan-800',
            'bg-skin-yellow': 'scrollbar-thumb-amber-600',
            'bg-skin-yellow-light': 'scrollbar-thumb-amber-300',
            'bg-skin-green': 'scrollbar-thumb-green-700',
            'bg-skin-green-light': 'scrollbar-thumb-green-700',
            'bg-skin-purple': 'scrollbar-thumb-pink-800',
            'bg-skin-purple-light': 'scrollbar-thumb-pink-600',
            'bg-skin-red': 'scrollbar-thumb-red-600',
            'bg-skin-red-light': 'scrollbar-thumb-red-600',
            'bg-skin-black': 'scrollbar-thumb-gray-900',
            'bg-skin-black-light': 'scrollbar-thumb-gray-800',
            'bg-skin-white': 'scrollbar-thumb-sky-700',
        }

    };

    return {
        textColor: styles.textColor[theme],
        textColorActive: styles.textColorActive[theme],
        hoverTextColor: styles.hoverTextColor[theme],
        bgColor: styles.bgColor[theme],
        borderColor: styles.borderColor[theme],
        tooltipColor: styles.tooltipColor[theme],
        arrwoTooltipColor: styles.arrwoTooltipColor[theme],
        buttonSwalColor: styles.buttonSwalColor[theme],
        paginationHoverColor: styles.paginationHoverColor[theme],
        primayActiveColor: styles.primayActiveColor[theme],
        paginationSideActiveColor: styles.paginationSideActiveColor[theme],
        hoverColor: styles.hoverColor[theme],
        borderTheme: styles.borderTheme[theme],
        secondaryHoverBorderTheme: styles.secondaryHoverBorderTheme[theme],
        calendarDateTimeColor: styles.calendarDateTimeColor[theme],
        iconThemeColor: styles.iconThemeColor[theme],
        scrollbarTheme: styles.scrollbarTheme[theme]
    };
};

export default useThemeStyles;
